version: '3'

services: 
    bucky_db:
        image: mysql:5.7
        container_name: bucky_db
        volumes: 
        - bucky_db_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: bucky
            MYSQL_USER: bucky
            MYSQL_PASSWORD: bucky
        ports: 
            - 7002:3306
            
    bucky_api:
        container_name: bucky_api
        depends_on: 
            - bucky_db
        build: ./service.bucky.api
        volumes: 
        - ./service.bucky.api:/usr/src/app
        - /usr/src/app/node_modules
        ports: 
            - 7003:80
        env_file: 
            - ./service.bucky.api/env
volumes:
    bucky_db_data: