version: '3'

services: 
    service.bucky.api:
        build: ./service.bucky.api
        volumes: 
        - ./service.bucky.api:/usr/src/app
        - /usr/src/app/node_modules
        ports: 
            - 7003:80